DROP TABLE LOAN_TYPE;
CREATE TABLE LOAN_TYPE(
TYPE VARCHAR(10) NOT NULL PRIMARY KEY,
INTEREST_RATES DECIMAL(4,2)
);

INSERT INTO LOAN_TYPE VALUES('CREDITCARD',34.5);
INSERT INTO LOAN_TYPE VALUES('MORTGAGE',8.0);
INSERT INTO LOAN_TYPE VALUES('VEHICLE',7.5);

COMMIT;

SELECT * FROM LOAN_TYPE;